# !/usr/bin/python
# coding=utf-8
"""Base test configuration and utilities for UITK test suite.

This module provides common test infrastructure, fixtures, and utilities
used across all UITK test modules.
"""

import sys
import os
import logging
from pathlib import Path
from typing import Optional, Union
from unittest import TestCase

# Add package root and test directory to path for imports
PACKAGE_ROOT = Path(__file__).parent.parent.absolute()
TEST_DIR = Path(__file__).parent.absolute()
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))
if str(TEST_DIR) not in sys.path:
    sys.path.insert(0, str(TEST_DIR))


def setup_qt_application():
    """Ensure a QApplication instance exists for Qt-based tests.

    Returns:
        QApplication: The existing or newly created QApplication instance.
    """
    from qtpy import QtWidgets

    app = QtWidgets.QApplication.instance()
    if app is None:
        app = QtWidgets.QApplication(sys.argv)
    return app


class BaseTestCase(TestCase):
    """Base test case with common setup and utilities for UITK tests."""

    # Class-level logger
    logger: Optional[logging.Logger] = None

    @classmethod
    def setUpClass(cls):
        """Set up class-level resources."""
        cls.logger = logging.getLogger(cls.__name__)
        cls.logger.setLevel(logging.DEBUG)

    @classmethod
    def tearDownClass(cls):
        """Clean up class-level resources."""
        pass

    def setUp(self):
        """Set up test fixtures."""
        self.test_name = self._testMethodName
        if self.logger:
            self.logger.debug(f"Starting test: {self.test_name}")

    def tearDown(self):
        """Tear down test fixtures."""
        if self.logger:
            self.logger.debug(f"Completed test: {self.test_name}")


class QtBaseTestCase(BaseTestCase):
    """Base test case for Qt widget tests.

    Provides automatic QApplication setup and widget cleanup.
    """

    app = None
    _widgets_to_cleanup = None

    @classmethod
    def setUpClass(cls):
        """Set up Qt application for the test class."""
        super().setUpClass()
        cls.app = setup_qt_application()

    def setUp(self):
        """Set up test fixtures with widget tracking."""
        super().setUp()
        self._widgets_to_cleanup = []

    def tearDown(self):
        """Clean up widgets created during the test."""
        super().tearDown()
        if self._widgets_to_cleanup:
            for widget in self._widgets_to_cleanup:
                try:
                    widget.deleteLater()
                except RuntimeError:
                    # Widget may already be deleted
                    pass
            self._widgets_to_cleanup.clear()

    def track_widget(self, widget):
        """Register a widget for automatic cleanup.

        Args:
            widget: A Qt widget to be cleaned up after the test.

        Returns:
            The widget (for chaining).
        """
        if self._widgets_to_cleanup is not None:
            self._widgets_to_cleanup.append(widget)
        return widget

    # --- Visual Regression Helpers ---

    # Override in subclass or per-repo to change locations.
    SNAPSHOT_BASELINE_DIR: Optional[Path] = TEST_DIR / "snapshots"
    SNAPSHOT_OUTPUT_DIR: Optional[Path] = TEST_DIR / "temp_tests" / "snapshots"

    def capture_widget(self, widget, name: str) -> Path:
        """Capture a widget screenshot and save to the output directory.

        Args:
            widget: The Qt widget to capture.
            name: A short identifier (used as filename stem).

        Returns:
            Path to the saved PNG file.
        """
        from qtpy.QtWidgets import QApplication

        # Ensure pending events are processed so the widget is fully painted.
        QApplication.processEvents()

        output_dir = self.SNAPSHOT_OUTPUT_DIR
        output_dir.mkdir(parents=True, exist_ok=True)
        path = output_dir / f"{name}.png"
        pixmap = widget.grab()
        pixmap.save(str(path))
        return path

    def assert_visual_match(
        self,
        widget,
        name: str,
        *,
        threshold: float = 0.0,
        update_baseline: bool = False,
    ):
        """Assert that a widget's current appearance matches a stored baseline.

        On the first run (no baseline exists) or when *update_baseline* is True
        the current screenshot is saved as the new baseline and the assertion
        is skipped — so tests pass on the first run and baselines can be
        regenerated by setting the flag.

        Args:
            widget: The Qt widget to capture and compare.
            name: Baseline identifier (also the filename stem).
            threshold: Maximum allowed fraction (0.0–1.0) of pixels that may
                differ before the assertion fails. 0.0 means an exact match.
            update_baseline: If True, overwrite the baseline with the current
                screenshot and skip the comparison.

        Raises:
            AssertionError: If the images differ beyond *threshold*.
        """
        current_path = self.capture_widget(widget, name)

        baseline_dir = self.SNAPSHOT_BASELINE_DIR
        baseline_dir.mkdir(parents=True, exist_ok=True)
        baseline_path = baseline_dir / f"{name}.png"

        if update_baseline or not baseline_path.exists():
            import shutil

            shutil.copy2(current_path, baseline_path)
            return  # Nothing to compare yet.

        from PIL import Image, ImageChops

        baseline_img = Image.open(baseline_path).convert("RGBA")
        current_img = Image.open(current_path).convert("RGBA")

        if baseline_img.size != current_img.size:
            # Save diff artifacts for debugging before failing.
            self.fail(
                f"Visual size mismatch for '{name}': "
                f"baseline {baseline_img.size} vs current {current_img.size}. "
                f"Current screenshot saved at {current_path}"
            )

        diff = ImageChops.difference(baseline_img, current_img)
        # Count pixels where any channel differs.
        diff_pixels = sum(1 for px in diff.getdata() if px != (0, 0, 0, 0))
        total_pixels = baseline_img.size[0] * baseline_img.size[1]
        diff_ratio = diff_pixels / total_pixels if total_pixels else 0.0

        if diff_ratio > threshold:
            # Save the diff image for visual inspection.
            diff_path = self.SNAPSHOT_OUTPUT_DIR / f"{name}_diff.png"
            diff.save(str(diff_path))
            self.fail(
                f"Visual mismatch for '{name}': {diff_ratio:.4%} pixels differ "
                f"(threshold {threshold:.4%}). "
                f"Diff saved at {diff_path}"
            )

    @staticmethod
    def qtest():
        """Return the QTest module for synthetic input simulation.

        Usage::

            QTest = self.qtest()
            QTest.mouseClick(button, Qt.LeftButton)
            QTest.keyClicks(line_edit, "hello")
        """
        from qtpy.QtTest import QTest

        return QTest


# Test data paths (TEST_DIR already defined at top)
UITK_DIR = PACKAGE_ROOT / "uitk"
EXAMPLES_DIR = UITK_DIR / "examples"
WIDGETS_DIR = UITK_DIR / "widgets"


def get_test_resource_path(relative_path: str) -> Path:
    """Get the absolute path to a test resource.

    Args:
        relative_path: Path relative to the test directory.

    Returns:
        Absolute path to the resource.
    """
    return TEST_DIR / relative_path


def get_uitk_path(relative_path: str) -> Path:
    """Get the absolute path to a UITK module or resource.

    Args:
        relative_path: Path relative to the uitk package directory.

    Returns:
        Absolute path to the resource.
    """
    return UITK_DIR / relative_path
